src/GeekStream.WebUI/Models/ErrorViewModel.cs
using System;

namespace GeekStream.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/GeekStream.WebUI/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GeekStream.Domain.Entities;
using GeekStream.Infrastructure.DataAccess;

namespace GeekStream.WebUI.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArticlesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Articles.ToListAsync());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Content,Title,Tags,Rating,Id,PublishedDate")] Article article)
        {
            if (ModelState.IsValid)
            {
                _context.Add(article);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Content,Title,Tags,Rating,Id,PublishedDate")] Article article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _context.Articles.FindAsync(id);
            _context.Articles.Remove(article);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return _context.Articles.Any(e => e.Id == id);
        }
    }
}

src/GeekStream.WebUI/Controllers/HomeController.cs
using GeekStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GeekStream.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/GeekStream.WebUI/Views/Articles/Create.cshtml
@model GeekStream.Domain.Entities.Article

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishedDate" class="control-label"></label>
                <input asp-for="PublishedDate" class="form-control" />
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/GeekStream.WebUI/Views/Articles/Delete.cshtml
@model GeekStream.Domain.Entities.Article

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/GeekStream.WebUI/Views/Articles/Details.cshtml
@model GeekStream.Domain.Entities.Article

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/GeekStream.WebUI/Views/Articles/Edit.cshtml
@model GeekStream.Domain.Entities.Article

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PublishedDate" class="control-label"></label>
                <input asp-for="PublishedDate" class="form-control" />
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/GeekStream.WebUI/Views/Articles/Index.cshtml
@model IEnumerable<GeekStream.Domain.Entities.Article>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        div.rounded1 {
            border-radius: 25px;
            padding: 25px;
            background-color: #fff;
        }
        div.left {
            width: 70%;
            display: inline-block;
        }
        div.right {
            width: 20%;
            display: inline-block;
        }
    </style>
</head>

<h1>All Articles</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <div class="rounded1">
                    <h2 style="color:#383838">
                        @Html.DisplayFor(modelItem => item.Title)
                    </h2>
                    <h5 style="color:#828282">
                        @Html.DisplayFor(modelItem => item.Content)
                    </h5>
                    <br>
                    <h5 style="color:#828282">
                        @Html.DisplayFor(modelItem => item.PublishedDate)
                    </h5>
                    <div class="left">
                        <h5 style="color:#828282; font-style:italic">
                            Tags: @Html.DisplayFor(modelItem => item.Tags)
                        </h5>
                    </div>
                    <div class="right">
                        <h5 style="color:#828282">
                            Rating: @Html.DisplayFor(modelItem => item.Rating)
                        </h5>
                    </div>
                    <div>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </div>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>

src/GeekStream.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/GeekStream.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeekStream</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid body-content">
                <a class="navbar-brand" asp-area="" asp-controller="Articles" asp-action="Index">
                    <img src="/images/logo.png" alt="Logo" style="width:40px;">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Articles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Create">Create article</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-main">
        <div id="st-box">
            <ul>
                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.                        </li>
                <li>Mauris pulvinar orci sed lacinia placerat.                                      </li>
                <li>Morbi in ipsum quis lacus pretium blandit vel in ligula.                        </li>
                <li>Donec et justo ultricies lorem blandit facilisis scelerisque quis massa.        </li>
                <li>Proin sed risus faucibus, mattis risus quis, convallis sem.                     </li>
                <li>Suspendisse in augue et dui ornare interdum a a enim.                           </li>
                <li>Morbi mollis enim id nunc tempor facilisis.                                     </li>
                <li>Donec ut eros accumsan ex ornare condimentum.                                   </li>
                <li>Duis viverra dolor nec risus aliquet sagittis.                                  </li>
                <li>In egestas diam nec pellentesque pretium.                                       </li>
                <li>Integer non dolor sed lorem tempus hendrerit non ac massa.                      </li>
                <li>Sed tempor sapien vel tempor dictum.                                            </li>
                <li>Mauris blandit justo at efficitur finibus.                                      </li>
                <li>Mauris sed erat varius nisl condimentum gravida et a quam.                      </li>
                <li>Sed fermentum magna a felis luctus, sit amet tristique mi consequat.            </li>
                <li>Fusce eget arcu in mi tristique ornare in ac ex.                                </li>
                <li>Morbi aliquet lacus sit amet ligula porta, euismod dictum orci lobortis.        </li>
                <li>Proin eu urna consectetur, cursus nibh at, euismod leo.                         </li>
                <li>Sed id nisi in urna varius iaculis at id ante.                                  </li>
            </ul>
        </div>
        <div id="nd-box">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <div id="rd-box">
            <ul>
                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.                        </li>
                <li>Mauris pulvinar orci sed lacinia placerat.                                      </li>
                <li>Morbi in ipsum quis lacus pretium blandit vel in ligula.                        </li>
                <li>Donec et justo ultricies lorem blandit facilisis scelerisque quis massa.        </li>
                <li>Proin sed risus faucibus, mattis risus quis, convallis sem.                     </li>
                <li>Suspendisse in augue et dui ornare interdum a a enim.                           </li>
                <li>Morbi mollis enim id nunc tempor facilisis.                                     </li>
                <li>Donec ut eros accumsan ex ornare condimentum.                                   </li>
                <li>Duis viverra dolor nec risus aliquet sagittis.                                  </li>
                <li>In egestas diam nec pellentesque pretium.                                       </li>
                <li>Integer non dolor sed lorem tempus hendrerit non ac massa.                      </li>
                <li>Sed tempor sapien vel tempor dictum.                                            </li>
                <li>Mauris blandit justo at efficitur finibus.                                      </li>
                <li>Mauris sed erat varius nisl condimentum gravida et a quam.                      </li>
                <li>Sed fermentum magna a felis luctus, sit amet tristique mi consequat.            </li>
                <li>Fusce eget arcu in mi tristique ornare in ac ex.                                </li>
                <li>Morbi aliquet lacus sit amet ligula porta, euismod dictum orci lobortis.        </li>
                <li>Proin eu urna consectetur, cursus nibh at, euismod leo.                         </li>
                <li>Sed id nisi in urna varius iaculis at id ante.                                  </li>
            </ul>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid body-content">
            &copy; 2021 - GeekStream - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>